name: Marina CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 14
        os:
          - ubuntu-latest

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Nigiri
        run: |
          mkdir -p tmp; cd tmp
          curl https://travis.nigiri.network | bash; cd ..
          docker-compose -f  tmp/docker-compose.yml up -d

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bundle app
        run: yarn run build
      - name: Package the extension
        run: yarn run web-ext:build

      - name: Lint
        run: |
          yarn lint
          yarn prettier:check

      - name: Test
        run: yarn test
        env:
          CI: true
