name: Marina CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 14
        os:
          - ubuntu-latest

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: Reconfigure git to use HTTP authentication
        run: > 
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Nigiri
        run: |
          mkdir -p tmp; cd tmp
          curl https://travis.nigiri.network | bash; cd ..
          docker-compose -f  tmp/docker-compose.yml up -d

      - name: Install dependencies
        run: npm install --ci

      - name: Bundle app
        run: npm run build
      - name: Package the extension
        run: npm run web-ext:build

      - name: Lint
        run: |
          npm run lint
          npm run prettier:check

      - name: Test
        run: npm run test
        env:
          CI: true
